
import { Client, PaymentMethod, Owner, OwnerType, Product, ProductUnit, Cargo, CargoType, CargoStatus, Driver, DriverClassification, Vehicle, VehicleSetType, VehicleBodyType, Shipment, ShipmentStatus, User, UserProfile, DailyScheduleType } from './types';

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'CLI-001',
    razaoSocial: 'AGROPECUARIA SOL NASCENTE LTDA',
    nomeFantasia: 'Fazenda Sol Nascente',
    cnpj: '12.345.678/0001-99',
    phone: '(66) 99876-5432',
    email: 'contato@solnascente.com',
    address: 'Rodovia BR-163, Km 820',
    city: 'Sinop',
    state: 'MT',
    paymentMethod: PaymentMethod.Prazo,
    paymentTerm: 30,
    requiresExternalOrder: true,
    requiresScheduling: true,
  },
  {
    id: 'CLI-002',
    razaoSocial: 'GRÃOS DO BRASIL S.A.',
    nomeFantasia: 'Grãos Brasil',
    cnpj: '98.765.432/0001-11',
    phone: '(65) 98765-1234',
    email: 'financeiro@graosbrasil.com',
    address: 'Av. das Torres, 1500',
    city: 'Cuiabá',
    state: 'MT',
    paymentMethod: PaymentMethod.Boleto,
    paymentTerm: 21,
    requiresExternalOrder: false,
    requiresScheduling: true,
  },
  {
    id: 'CLI-003',
    razaoSocial: 'FERTILIZANTES CAMPO VERDE LTDA',
    nomeFantasia: 'Fertilizantes Campo Verde',
    cnpj: '11.222.333/0001-44',
    phone: '(11) 91234-5678',
    email: 'compras@campo-verde.com',
    address: 'Rua das Orquídeas, 45',
    city: 'São Paulo',
    state: 'SP',
    paymentMethod: PaymentMethod.Pix,
    paymentTerm: 0,
    requiresExternalOrder: false,
    requiresScheduling: false,
  },
  {
    id: 'CLI-004',
    razaoSocial: 'OURO SAFRA AGRICOLA LTDA',
    nomeFantasia: 'Ouro Safra',
    cnpj: '22.333.444/0001-55',
    phone: '(62) 99999-1111',
    email: 'contato@ourosafra.com',
    address: 'Av. Goias, 100',
    city: 'Goiânia',
    state: 'GO',
    paymentMethod: PaymentMethod.Prazo,
    paymentTerm: 25,
    requiresExternalOrder: true,
    requiresScheduling: false,
  },
  {
    id: 'CLI-005',
    razaoSocial: 'AGROMERCANTIL COMERCIO DE GRAOS',
    nomeFantasia: 'Agromercantil',
    cnpj: '33.444.555/0001-66',
    phone: '(77) 98888-2222',
    email: 'financeiro@agromercantil.com',
    address: 'Rua do Soja, 200',
    city: 'Luís Eduardo Magalhães',
    state: 'BA',
    paymentMethod: PaymentMethod.Boleto,
    paymentTerm: 15,
    requiresExternalOrder: false,
    requiresScheduling: true,
  },
  {
    id: 'CLI-006',
    razaoSocial: 'MMJV PARTICIPACOES S.A.',
    nomeFantasia: 'MMJV',
    cnpj: '44.555.666/0001-77',
    phone: '(21) 97777-3333',
    email: 'operacoes@mmjv.com',
    address: 'Av. Brasil, 3000',
    city: 'Rio de Janeiro',
    state: 'RJ',
    paymentMethod: PaymentMethod.Prazo,
    paymentTerm: 45,
    requiresExternalOrder: true,
    requiresScheduling: true,
  },
  {
    id: 'CLI-007',
    razaoSocial: 'GRAO DE OURO ARMAZENS GERAIS',
    nomeFantasia: 'Grão de Ouro',
    cnpj: '55.666.777/0001-88',
    phone: '(16) 96666-4444',
    email: 'logistica@graodeouro.com',
    address: 'Rod. Anhanguera, Km 310',
    city: 'Ribeirão Preto',
    state: 'SP',
    paymentMethod: PaymentMethod.Pix,
    paymentTerm: 0,
    requiresExternalOrder: false,
    requiresScheduling: false,
  },
];

export const MOCK_OWNERS: Owner[] = [
  {
    id: 'OWN-001',
    name: 'João da Silva Transportes ME',
    cpfCnpj: '22.111.333/0001-05',
    phone: '(66) 98765-4321',
    type: OwnerType.PessoaJuridica,
    bankDetails: 'Banco Brasil | Ag: 1234 | CC: 56789-0',
  },
  {
    id: 'OWN-002',
    name: 'Maria Oliveira',
    cpfCnpj: '123.456.789-00',
    phone: '(11) 91234-5678',
    type: OwnerType.PessoaFisica,
    bankDetails: 'NuBank | Ag: 0001 | CC: 112233-4',
  },
  {
    id: 'OWN-003',
    name: 'Frota Rápida Logística LTDA',
    cpfCnpj: '45.678.123/0001-21',
    phone: '(65) 99988-7766',
    type: OwnerType.PessoaJuridica,
    bankDetails: 'Sicoob | Ag: 3322 | CC: 44556-7',
  },
  {
    id: 'OWN-999',
    name: 'PROPRIETÁRIO PADRÃO TERCEIRO',
    cpfCnpj: '00.000.000/0000-00',
    phone: '',
    type: OwnerType.PessoaJuridica,
    bankDetails: '',
  },
];

export const MOCK_DRIVERS: Driver[] = [
  { id: 'DRV-001', name: 'Carlos Pereira', cpf: '111.222.333-44', cnh: '123456789', phone: '(66) 91111-2222', classification: DriverClassification.Agregado, ownerId: 'OWN-001' },
  { id: 'DRV-002', name: 'Maria Oliveira', cpf: '123.456.789-00', cnh: '987654321', phone: '(11) 91234-5678', classification: DriverClassification.Proprio, ownerId: 'OWN-002' },
  { id: 'DRV-003', name: 'Roberto Souza', cpf: '444.555.666-77', cnh: '555444333', phone: '(65) 93333-4444', classification: DriverClassification.Frota, ownerId: 'OWN-003' },
];

export const MOCK_VEHICLES: Vehicle[] = [
    { id: 'VEH-001', plate: 'ABC-1234', setType: VehicleSetType.LSSimples, bodyType: VehicleBodyType.Graneleiro, classification: DriverClassification.Agregado, ownerId: 'OWN-001', driverId: 'DRV-001' },
    { id: 'VEH-002', plate: 'DEF-5678', setType: VehicleSetType.Bitrem7e, bodyType: VehicleBodyType.Basculante, classification: DriverClassification.Proprio, ownerId: 'OWN-002', driverId: 'DRV-002' },
    { id: 'VEH-003', plate: 'GHI-9012', setType: VehicleSetType.Rodotrem, bodyType: VehicleBodyType.Graneleiro, classification: DriverClassification.Frota, ownerId: 'OWN-003', driverId: 'DRV-003' },
];


export const MOCK_PRODUCTS: Product[] = [
    { id: 'prod_1', name: 'Soja a Granel', unit: ProductUnit.Tonelada },
    { id: 'prod_2', name: 'Milho em Sacas', unit: ProductUnit.Sacas },
    { id: 'prod_3', name: 'Fertilizante NPK', unit: ProductUnit.Tonelada },
];

export const MOCK_CARGOS: Cargo[] = [
    {
        id: 'CRG-001',
        sequenceId: 101,
        clientId: 'CLI-001',
        productId: 'prod_1',
        origin: 'Sinop, MT',
        destination: 'Santos, SP',
        totalVolume: 5000,
        scheduledVolume: 73.5,
        loadedVolume: 35.5,
        companyFreightValuePerTon: 220,
        driverFreightValuePerTon: 180,
        hasIcms: true,
        icmsPercentage: 12,
        requiresScheduling: true,
        type: CargoType.Fixa,
        status: CargoStatus.EmAndamento,
        createdAt: new Date('2024-05-01T10:00:00Z').toISOString(),
        createdById: 'USR-003',
        allowedVehicleTypes: [{ setType: VehicleSetType.LSSimples, bodyTypes: [VehicleBodyType.Graneleiro, VehicleBodyType.Basculante] }],
        dailySchedule: [
            { date: '2024-07-28', type: DailyScheduleType.Fixo, tonnage: 120 },
            { date: '2024-07-29', type: DailyScheduleType.Verificar },
            { date: '2024-07-30', type: DailyScheduleType.Livre },
        ],
        history: [{ id: 'log_1', userId: 'USR-003', timestamp: new Date('2024-05-01T10:00:00Z').toISOString(), description: 'Carga criada.' }],
        observations: 'Carga com necessidade de agendamento prévio de 48h. Contatar o cliente para alinhar a janela de coleta.',
        attachments: ['contrato_sol_nascente.pdf'],
    },
    {
        id: 'CRG-002',
        sequenceId: 102,
        clientId: 'CLI-002',
        productId: 'prod_2',
        origin: 'Sorriso, MT',
        destination: 'Paranaguá, PR',
        totalVolume: 10000,
        scheduledVolume: 87.8,
        loadedVolume: 45.0,
        companyFreightValuePerTon: 190,
        driverFreightValuePerTon: 165,
        hasIcms: false,
        icmsPercentage: 0,
        requiresScheduling: false,
        type: CargoType.Spot,
        status: CargoStatus.EmAndamento,
        createdAt: new Date('2024-05-10T14:30:00Z').toISOString(),
        createdById: 'USR-004',
        history: [{ id: 'log_2', userId: 'USR-004', timestamp: new Date('2024-05-10T14:30:00Z').toISOString(), description: 'Carga criada.' }],
        observations: '',
        attachments: [],
    },
    {
        id: 'CRG-003',
        sequenceId: 103,
        clientId: 'CLI-001',
        productId: 'prod_1',
        origin: 'Sinop, MT',
        destination: 'Paranaguá, PR',
        totalVolume: 2500,
        scheduledVolume: 46.1,
        loadedVolume: 46.1,
        companyFreightValuePerTon: 205,
        driverFreightValuePerTon: 175,
        hasIcms: false,
        icmsPercentage: 0,
        requiresScheduling: true,
        type: CargoType.Fixa,
        status: CargoStatus.Fechada,
        createdAt: new Date('2024-04-15T09:00:00Z').toISOString(),
        createdById: 'USR-003',
        allowedVehicleTypes: [{ setType: VehicleSetType.LSSimples, bodyTypes: [VehicleBodyType.Graneleiro] }],
        history: [{ id: 'log_3', userId: 'USR-003', timestamp: new Date('2024-04-15T09:00:00Z').toISOString(), description: 'Carga criada.' }],
        observations: 'Carga finalizada. Todos os embarques concluídos.',
        attachments: [],
    },
    {
        id: 'CRG-004',
        sequenceId: 104,
        clientId: 'CLI-003',
        productId: 'prod_3',
        origin: 'Catalão, GO',
        destination: 'Santos, SP',
        totalVolume: 3000,
        scheduledVolume: 205,
        loadedVolume: 0,
        companyFreightValuePerTon: 200,
        driverFreightValuePerTon: 180,
        hasIcms: true,
        icmsPercentage: 10,
        requiresScheduling: false,
        type: CargoType.Spot,
        status: CargoStatus.EmAndamento,
        createdAt: new Date().toISOString(),
        createdById: 'USR-003',
        history: [{ id: 'log_10', userId: 'USR-003', timestamp: new Date().toISOString(), description: 'Carga criada.' }],
    },
    {
        id: 'CRG-005',
        sequenceId: 105,
        clientId: 'CLI-004',
        productId: 'prod_1',
        origin: 'Uberlândia, MG',
        destination: 'Santos, SP',
        totalVolume: 5000,
        scheduledVolume: 203,
        loadedVolume: 0,
        companyFreightValuePerTon: 200,
        driverFreightValuePerTon: 180,
        hasIcms: false,
        icmsPercentage: 0,
        requiresScheduling: true,
        type: CargoType.Fixa,
        status: CargoStatus.EmAndamento,
        createdAt: new Date().toISOString(),
        createdById: 'USR-004',
        history: [{ id: 'log_11', userId: 'USR-004', timestamp: new Date().toISOString(), description: 'Carga criada.' }],
    },
    {
        id: 'CRG-006',
        sequenceId: 106,
        clientId: 'CLI-005',
        productId: 'prod_1',
        origin: 'Patrocínio, MG',
        destination: 'Santos, SP',
        totalVolume: 4000,
        scheduledVolume: 170,
        loadedVolume: 85,
        companyFreightValuePerTon: 200,
        driverFreightValuePerTon: 180,
        hasIcms: true,
        icmsPercentage: 12,
        requiresScheduling: false,
        type: CargoType.Spot,
        status: CargoStatus.EmAndamento,
        createdAt: new Date().toISOString(),
        createdById: 'USR-003',
        history: [{ id: 'log_12', userId: 'USR-003', timestamp: new Date().toISOString(), description: 'Carga criada.' }],
    },
    {
        id: 'CRG-007',
        sequenceId: 107,
        clientId: 'CLI-006',
        productId: 'prod_2',
        origin: 'Guarda-Mor, MG',
        destination: 'Santos, SP',
        totalVolume: 6000,
        scheduledVolume: 116,
        loadedVolume: 40,
        companyFreightValuePerTon: 200,
        driverFreightValuePerTon: 180,
        hasIcms: false,
        icmsPercentage: 0,
        requiresScheduling: false,
        type: CargoType.Fixa,
        status: CargoStatus.EmAndamento,
        createdAt: new Date().toISOString(),
        createdById: 'USR-004',
        history: [{ id: 'log_13', userId: 'USR-004', timestamp: new Date().toISOString(), description: 'Carga criada.' }],
    },
];

export const MOCK_SHIPMENTS: Shipment[] = [
    {
        id: 'SHP-001',
        orderId: 'ORD-001',
        cargoId: 'CRG-001',
        driverName: 'Carlos Pereira',
        driverContact: '(66) 91111-2222',
        embarcadorId: 'USR-009',
        horsePlate: 'ABC-1234',
        shipmentTonnage: 35.5,
        driverFreightValue: 35.5 * 180,
        status: ShipmentStatus.AguardandoDescarga,
        scheduledDate: '2024-07-28',
        scheduledTime: '14:00',
        createdAt: new Date('2024-05-02T11:00:00Z').toISOString(),
        createdById: 'USR-009',
        history: [{ id: 'log_4', userId: 'USR-009', timestamp: new Date().toISOString(), description: 'Embarque criado.' }],
        statusHistory: [
            { status: ShipmentStatus.PreCadastro, timestamp: new Date('2024-05-02T11:00:00Z').toISOString(), userId: 'USR-009' },
            { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date('2024-05-02T12:00:00Z').toISOString(), userId: 'USR-006' },
            { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date('2024-05-03T08:00:00Z').toISOString(), userId: 'USR-006' },
            { status: ShipmentStatus.AguardandoNota, timestamp: new Date('2024-05-03T14:00:00Z').toISOString(), userId: 'USR-006' },
            { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date('2024-05-03T16:00:00Z').toISOString(), userId: 'USR-007' },
            { status: ShipmentStatus.AguardandoDescarga, timestamp: new Date('2024-05-04T09:00:00Z').toISOString(), userId: 'USR-007' },
        ],
    },
    {
        id: 'SHP-002',
        orderId: 'ORD-002',
        cargoId: 'CRG-001',
        driverName: 'Roberto Souza',
        driverContact: '(65) 93333-4444',
        embarcadorId: 'USR-009',
        horsePlate: 'GHI-9012',
        shipmentTonnage: 38.0,
        driverFreightValue: 38.0 * 180,
        status: ShipmentStatus.AguardandoCarregamento,
        scheduledDate: '2024-07-28',
        scheduledTime: '16:30',
        createdAt: new Date('2024-05-05T15:00:00Z').toISOString(),
        createdById: 'USR-009',
        history: [{ id: 'log_5', userId: 'USR-009', timestamp: new Date().toISOString(), description: 'Embarque criado.' }],
        statusHistory: [
             { status: ShipmentStatus.PreCadastro, timestamp: new Date('2024-05-05T15:00:00Z').toISOString(), userId: 'USR-009' },
             { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date('2024-05-05T16:00:00Z').toISOString(), userId: 'USR-006' },
             { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date('2024-05-06T09:00:00Z').toISOString(), userId: 'USR-006' },
        ],
    },
    {
        id: 'SHP-003',
        orderId: 'ORD-003',
        cargoId: 'CRG-002',
        driverName: 'Maria Oliveira',
        driverContact: '(11) 91234-5678',
        embarcadorId: 'USR-010',
        horsePlate: 'DEF-5678',
        shipmentTonnage: 45.0,
        driverFreightValue: 45.0 * 165,
        status: ShipmentStatus.Finalizado,
        scheduledDate: '2024-05-12',
        createdAt: new Date('2024-05-11T10:00:00Z').toISOString(),
        createdById: 'USR-010',
        history: [{ id: 'log_6', userId: 'USR-010', timestamp: new Date().toISOString(), description: 'Embarque criado.' }],
        statusHistory: [{ status: ShipmentStatus.Finalizado, timestamp: new Date('2024-05-20T18:00:00Z').toISOString(), userId: 'USR-007' }],
    },
     {
        id: 'SHP-004',
        orderId: 'ORD-004',
        cargoId: 'CRG-002',
        driverName: 'Carlos Pereira',
        driverContact: '(66) 91111-2222',
        embarcadorId: 'USR-010',
        horsePlate: 'ABC-1234',
        shipmentTonnage: 42.8,
        driverFreightValue: 42.8 * 165,
        status: ShipmentStatus.AguardandoAdiantamento,
        scheduledDate: '2024-05-13',
        createdAt: new Date('2024-05-12T13:00:00Z').toISOString(),
        createdById: 'USR-010',
        history: [{ id: 'log_7', userId: 'USR-010', timestamp: new Date().toISOString(), description: 'Embarque criado.' }],
        statusHistory: [{ status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date('2024-05-12T13:00:00Z').toISOString(), userId: 'USR-010' }],
    },
    {
        id: 'SHP-005',
        orderId: 'ORD-005',
        cargoId: 'CRG-002',
        driverName: 'Roberto Souza',
        driverContact: '(65) 93333-4444',
        embarcadorId: 'USR-010',
        horsePlate: 'GHI-9012',
        shipmentTonnage: 44.2,
        driverFreightValue: 44.2 * 165,
        status: ShipmentStatus.Cancelado,
        scheduledDate: '2024-05-14',
        createdAt: new Date('2024-05-13T09:00:00Z').toISOString(),
        createdById: 'USR-010',
        history: [{ id: 'log_8', userId: 'USR-010', timestamp: new Date().toISOString(), description: 'Embarque criado e depois cancelado.' }],
        statusHistory: [{ status: ShipmentStatus.Cancelado, timestamp: new Date('2024-05-14T10:00:00Z').toISOString(), userId: 'USR-003' }],
    },
     {
        id: 'SHP-006',
        orderId: 'ORD-006',
        cargoId: 'CRG-003',
        driverName: 'Maria Oliveira',
        driverContact: '(11) 91234-5678',
        embarcadorId: 'USR-009',
        horsePlate: 'DEF-5678',
        shipmentTonnage: 46.1,
        driverFreightValue: 46.1 * 175,
        status: ShipmentStatus.Finalizado,
        scheduledDate: '2024-04-19',
        createdAt: new Date('2024-04-18T11:00:00Z').toISOString(),
        createdById: 'USR-009',
        history: [{ id: 'log_9', userId: 'USR-009', timestamp: new Date().toISOString(), description: 'Embarque criado.' }],
        statusHistory: [{ status: ShipmentStatus.Finalizado, timestamp: new Date('2024-04-28T16:00:00Z').toISOString(), userId: 'USR-007' }],
    },
    // --- NEW MOCK DATA ---
    { id: 'SHP-007', orderId: 'ORD-007', cargoId: 'CRG-004', driverName: 'Carlos Pereira', embarcadorId: 'USR-009', horsePlate: 'ABC-1234', shipmentTonnage: 40, driverFreightValue: 7200, status: ShipmentStatus.PreCadastro, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 60*60*1000).toISOString(), createdById: 'USR-009', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 60*60*1000).toISOString(), userId: 'USR-009' }] },
    { id: 'SHP-008', orderId: 'ORD-008', cargoId: 'CRG-005', driverName: 'Maria Oliveira', embarcadorId: 'USR-010', horsePlate: 'DEF-5678', shipmentTonnage: 42, driverFreightValue: 7560, status: ShipmentStatus.PreCadastro, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 90*60*1000).toISOString(), createdById: 'USR-010', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 90*60*1000).toISOString(), userId: 'USR-010' }] },
    { id: 'SHP-009', orderId: 'ORD-009', cargoId: 'CRG-004', driverName: 'Roberto Souza', embarcadorId: 'USR-011', horsePlate: 'GHI-9012', shipmentTonnage: 38, driverFreightValue: 6840, status: ShipmentStatus.AguardandoSeguradora, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 2*60*60*1000).toISOString(), createdById: 'USR-011', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 2*60*60*1000).toISOString(), userId: 'USR-011' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 40*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-010', orderId: 'ORD-010', cargoId: 'CRG-006', driverName: 'Carlos Pereira', embarcadorId: 'USR-012', horsePlate: 'ABC-1234', shipmentTonnage: 41, driverFreightValue: 7380, status: ShipmentStatus.AguardandoSeguradora, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 3*60*60*1000).toISOString(), createdById: 'USR-012', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 3*60*60*1000).toISOString(), userId: 'USR-012' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 60*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-011', orderId: 'ORD-011', cargoId: 'CRG-007', driverName: 'Maria Oliveira', embarcadorId: 'USR-009', horsePlate: 'DEF-5678', shipmentTonnage: 39, driverFreightValue: 7020, status: ShipmentStatus.AguardandoCarregamento, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 24*60*60*1000).toISOString(), createdById: 'USR-009', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 24*60*60*1000).toISOString(), userId: 'USR-009' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 22*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 20*60*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-012', orderId: 'ORD-012', cargoId: 'CRG-004', driverName: 'Roberto Souza', embarcadorId: 'USR-010', horsePlate: 'GHI-9012', shipmentTonnage: 43, driverFreightValue: 7740, status: ShipmentStatus.AguardandoCarregamento, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 25*60*60*1000).toISOString(), createdById: 'USR-010', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 25*60*60*1000).toISOString(), userId: 'USR-010' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 24*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 23*60*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-013', orderId: 'ORD-013', cargoId: 'CRG-005', driverName: 'Carlos Pereira', embarcadorId: 'USR-011', horsePlate: 'ABC-1234', shipmentTonnage: 40, driverFreightValue: 7200, status: ShipmentStatus.AguardandoNota, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 2*24*60*60*1000).toISOString(), createdById: 'USR-011', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 2*24*60*60*1000).toISOString(), userId: 'USR-011' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 47*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 46*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 3*60*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-014', orderId: 'ORD-014', cargoId: 'CRG-006', driverName: 'Maria Oliveira', embarcadorId: 'USR-012', horsePlate: 'DEF-5678', shipmentTonnage: 44, driverFreightValue: 7920, status: ShipmentStatus.AguardandoNota, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 3*24*60*60*1000).toISOString(), createdById: 'USR-012', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 3*24*60*60*1000).toISOString(), userId: 'USR-012' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 70*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 68*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 5*60*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-015', orderId: 'ORD-015', cargoId: 'CRG-007', driverName: 'Roberto Souza', embarcadorId: 'USR-009', horsePlate: 'GHI-9012', shipmentTonnage: 37, driverFreightValue: 6660, status: ShipmentStatus.AguardandoAdiantamento, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 4*24*60*60*1000).toISOString(), createdById: 'USR-009', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 4*24*60*60*1000).toISOString(), userId: 'USR-009' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 95*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 94*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 90*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 45*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-016', orderId: 'ORD-016', cargoId: 'CRG-004', driverName: 'Carlos Pereira', embarcadorId: 'USR-010', horsePlate: 'ABC-1234', shipmentTonnage: 45, driverFreightValue: 8100, status: ShipmentStatus.AguardandoAdiantamento, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 5*24*60*60*1000).toISOString(), createdById: 'USR-010', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 5*24*60*60*1000).toISOString(), userId: 'USR-010' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 110*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 108*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 100*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 90*60*1000).toISOString(), userId: 'USR-006' }] },
    { id: 'SHP-017', orderId: 'ORD-017', cargoId: 'CRG-005', driverName: 'Maria Oliveira', embarcadorId: 'USR-011', horsePlate: 'DEF-5678', shipmentTonnage: 41, driverFreightValue: 7380, status: ShipmentStatus.AguardandoAgendamento, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 6*24*60*60*1000).toISOString(), createdById: 'USR-011', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 6*24*60*60*1000).toISOString(), userId: 'USR-011' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 140*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 138*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 130*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 125*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoAgendamento, timestamp: new Date(Date.now() - 124*60*60*1000).toISOString(), userId: 'USR-007' }] },
    { id: 'SHP-018', orderId: 'ORD-018', cargoId: 'CRG-005', driverName: 'Roberto Souza', embarcadorId: 'USR-012', horsePlate: 'GHI-9012', shipmentTonnage: 39, driverFreightValue: 7020, status: ShipmentStatus.AguardandoAgendamento, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 7*24*60*60*1000).toISOString(), createdById: 'USR-012', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 7*24*60*60*1000).toISOString(), userId: 'USR-012' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 160*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 158*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 150*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 145*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoAgendamento, timestamp: new Date(Date.now() - 144*60*60*1000).toISOString(), userId: 'USR-007' }] },
    { id: 'SHP-019', orderId: 'ORD-019', cargoId: 'CRG-006', driverName: 'Carlos Pereira', embarcadorId: 'USR-009', horsePlate: 'ABC-1234', shipmentTonnage: 42, driverFreightValue: 7560, status: ShipmentStatus.AguardandoDescarga, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 8*24*60*60*1000).toISOString(), createdById: 'USR-009', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 8*24*60*60*1000).toISOString(), userId: 'USR-009' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 180*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 178*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 170*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 165*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoDescarga, timestamp: new Date(Date.now() - 164*60*60*1000).toISOString(), userId: 'USR-007' }] },
    { id: 'SHP-020', orderId: 'ORD-020', cargoId: 'CRG-007', driverName: 'Maria Oliveira', embarcadorId: 'USR-010', horsePlate: 'DEF-5678', shipmentTonnage: 40, driverFreightValue: 7200, status: ShipmentStatus.AguardandoDescarga, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 9*24*60*60*1000).toISOString(), createdById: 'USR-010', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 9*24*60*60*1000).toISOString(), userId: 'USR-010' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 200*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 198*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 190*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 185*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoDescarga, timestamp: new Date(Date.now() - 184*60*60*1000).toISOString(), userId: 'USR-007' }] },
    { id: 'SHP-021', orderId: 'ORD-021', cargoId: 'CRG-004', driverName: 'Roberto Souza', embarcadorId: 'USR-011', horsePlate: 'GHI-9012', shipmentTonnage: 39, driverFreightValue: 7020, status: ShipmentStatus.AguardandoPagamentoSaldo, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 10*24*60*60*1000).toISOString(), createdById: 'USR-011', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 10*24*60*60*1000).toISOString(), userId: 'USR-011' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 230*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 228*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 220*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 215*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoDescarga, timestamp: new Date(Date.now() - 100*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoPagamentoSaldo, timestamp: new Date(Date.now() - 25*60*60*1000).toISOString(), userId: 'USR-007' }] },
    { id: 'SHP-022', orderId: 'ORD-022', cargoId: 'CRG-005', driverName: 'Carlos Pereira', embarcadorId: 'USR-012', horsePlate: 'ABC-1234', shipmentTonnage: 41, driverFreightValue: 7380, status: ShipmentStatus.AguardandoPagamentoSaldo, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 11*24*60*60*1000).toISOString(), createdById: 'USR-012', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 11*24*60*60*1000).toISOString(), userId: 'USR-012' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 250*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoCarregamento, timestamp: new Date(Date.now() - 248*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoNota, timestamp: new Date(Date.now() - 240*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.AguardandoAdiantamento, timestamp: new Date(Date.now() - 235*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoAgendamento, timestamp: new Date(Date.now() - 230*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoDescarga, timestamp: new Date(Date.now() - 120*60*60*1000).toISOString(), userId: 'USR-007' }, { status: ShipmentStatus.AguardandoPagamentoSaldo, timestamp: new Date(Date.now() - 50*60*60*1000).toISOString(), userId: 'USR-007' }] },
    { id: 'SHP-023', orderId: 'ORD-023', cargoId: 'CRG-006', driverName: 'Maria Oliveira', embarcadorId: 'USR-009', horsePlate: 'DEF-5678', shipmentTonnage: 43, driverFreightValue: 7740, status: ShipmentStatus.Finalizado, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 12*24*60*60*1000).toISOString(), createdById: 'USR-009', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 12*24*60*60*1000).toISOString(), userId: 'USR-009' }, { status: ShipmentStatus.Finalizado, timestamp: new Date(Date.now() - 2*24*60*60*1000).toISOString(), userId: 'USR-007' }] },
    { id: 'SHP-024', orderId: 'ORD-024', cargoId: 'CRG-007', driverName: 'Roberto Souza', embarcadorId: 'USR-010', horsePlate: 'GHI-9012', shipmentTonnage: 40, driverFreightValue: 7200, status: ShipmentStatus.Cancelado, scheduledDate: new Date().toISOString().split('T')[0], createdAt: new Date(Date.now() - 13*24*60*60*1000).toISOString(), createdById: 'USR-010', history: [], statusHistory: [{ status: ShipmentStatus.PreCadastro, timestamp: new Date(Date.now() - 13*24*60*60*1000).toISOString(), userId: 'USR-010' }, { status: ShipmentStatus.AguardandoSeguradora, timestamp: new Date(Date.now() - 300*60*60*1000).toISOString(), userId: 'USR-006' }, { status: ShipmentStatus.Cancelado, timestamp: new Date(Date.now() - 290*60*60*1000).toISOString(), userId: 'USR-005' }] },
];


export const MOCK_USERS: User[] = [
  { id: 'USR-001', name: 'Kaique', email: 'kaique@rodochagas.com.br', profile: UserProfile.Admin, active: true, password: '123' },
  { id: 'USR-002', name: 'Robson', email: 'robson@rodochagas.com.br', profile: UserProfile.Diretor, active: true, password: '123' },
  { id: 'USR-003', name: 'Davi', email: 'davi@rodochagas.com.br', profile: UserProfile.Comercial, active: true, password: '123' },
  { id: 'USR-004', name: 'Bruno', email: 'bruno@rodochagas.com.br', profile: UserProfile.Comercial, active: true, password: '123' },
  { id: 'USR-005', name: 'Charles', email: 'charles@rodochagas.com.br', profile: UserProfile.Supervisor, active: true, password: '123' },
  { id: 'USR-006', name: 'Gustavo', email: 'gustavo.fiscal@rodochagas.com.br', profile: UserProfile.Fiscal, active: true, password: '123' },
  { id: 'USR-007', name: 'Leandro', email: 'leandro@rodochagas.com.br', profile: UserProfile.Financeiro, active: true, password: '123' },
  { id: 'USR-008', name: 'Amanda', email: 'amanda@rodochagas.com.br', profile: UserProfile.Supervisor, active: true, password: '123' },
  { id: 'USR-009', name: 'Samuel Oliveira', email: 'samuel@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-010', name: 'Elane', email: 'elane@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-011', name: 'Carlos', email: 'carlos@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-012', name: 'Gabriel', email: 'gabriel@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-013', name: 'Gustavo', email: 'gustavo.embarcador@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-014', name: 'Alessandro', email: 'alessandro@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-015', name: 'Renato', email: 'renato@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-016', name: 'Mateus', email: 'mateus@rodochagas.com.br', profile: UserProfile.Embarcador, active: true, password: '123' },
  { id: 'USR-017', name: 'Cliente Ouro Safra', email: 'ourosafra@cliente.com', profile: UserProfile.Cliente, active: true, password: '123', clientId: 'CLI-004' },
  { id: 'USR-018', name: 'Cliente Agromercantil', email: 'agromercantil@cliente.com', profile: UserProfile.Cliente, active: true, password: '123', clientId: 'CLI-005' },
  { id: 'USR-019', name: 'Cliente MMJV', email: 'mmjv@cliente.com', profile: UserProfile.Cliente, active: true, password: '123', clientId: 'CLI-006' },
  { id: 'USR-020', name: 'Cliente Grão de Ouro', email: 'graodeouro@cliente.com', profile: UserProfile.Cliente, active: true, password: '123', clientId: 'CLI-007' },
];
